// Canvas constants.
const WIDTH = 1900;
const HEIGHT = 1000;
const HORIZONTAL_BOUND = WIDTH/2;
const VERTICAL_LOWER_BOUND = HEIGHT/4;
const VERTICAL_UPPER_BOUND = HEIGHT - HEIGHT/10;
const LINE_WIDTH = WIDTH/300;
const LINE_X_POS = WIDTH/2;
const LINE_Y_POS = HEIGHT/2;
const TEXT_SIZE = WIDTH/60;
const REVISION_TEXT_X_POS = WIDTH/60;
const REVISION_TEXT_Y_POS = HEIGHT/15;
const DISTANCE_TEXT_X_POS = WIDTH/60;
const DISTANCE_TEXT_Y_POS = HEIGHT/7.5;
const BEST_REVISION_TEXT_X_POS = WIDTH/60+HORIZONTAL_BOUND;
const BEST_DISTANCE_TEXT_X_POS = WIDTH/60+HORIZONTAL_BOUND;
const CITY_SIZE = HEIGHT/50;
const STROKE_WEIGHT = WIDTH/500;
// Color constants.
const BACKGROUND_COLOR = 10;
const RED = [255, 0, 0];
const GREEN = [0, 255, 0];
const BLUE = [0, 0, 255];
const WHITE = 255;
// Salesman constants.
const OPTIMAL = true;
const NUM_CITIES = 20;
const NUM_ROUTES = 100;
const SET_SIZE = 3;
const ADJUSTMENT_RATE = 0.05;
